// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpi_compensator.h"

extern XPi_compensator_Config XPi_compensator_ConfigTable[];

XPi_compensator_Config *XPi_compensator_LookupConfig(u16 DeviceId) {
	XPi_compensator_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPI_COMPENSATOR_NUM_INSTANCES; Index++) {
		if (XPi_compensator_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPi_compensator_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPi_compensator_Initialize(XPi_compensator *InstancePtr, u16 DeviceId) {
	XPi_compensator_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPi_compensator_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPi_compensator_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

