// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdig_compensator.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDig_compensator_CfgInitialize(XDig_compensator *InstancePtr, XDig_compensator_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDig_compensator_Set_params_vRef(XDig_compensator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDig_compensator_WriteReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_VREF_DATA, Data);
}

u32 XDig_compensator_Get_params_vRef(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_VREF_DATA);
    return Data;
}

void XDig_compensator_Set_params_y_max(XDig_compensator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDig_compensator_WriteReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_Y_MAX_DATA, Data);
}

u32 XDig_compensator_Get_params_y_max(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_Y_MAX_DATA);
    return Data;
}

void XDig_compensator_Set_params_adcMask(XDig_compensator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDig_compensator_WriteReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_ADCMASK_DATA, Data);
}

u32 XDig_compensator_Get_params_adcMask(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_ADCMASK_DATA);
    return Data;
}

u32 XDig_compensator_Get_yVmeasDbg(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_YVMEASDBG_DATA);
    return Data;
}

u32 XDig_compensator_Get_yVmeasDbg_vld(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_YVMEASDBG_CTRL);
    return Data & 0x1;
}

u32 XDig_compensator_Get_yDbg(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_YDBG_DATA);
    return Data;
}

u32 XDig_compensator_Get_yDbg_vld(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_YDBG_CTRL);
    return Data & 0x1;
}

u32 XDig_compensator_Get_eDbg(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_EDBG_DATA);
    return Data;
}

u32 XDig_compensator_Get_eDbg_vld(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_EDBG_CTRL);
    return Data & 0x1;
}

u32 XDig_compensator_Get_uDbg(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_UDBG_DATA);
    return Data;
}

u32 XDig_compensator_Get_uDbg_vld(XDig_compensator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDig_compensator_ReadReg(InstancePtr->Axilites_BaseAddress, XDIG_COMPENSATOR_AXILITES_ADDR_UDBG_CTRL);
    return Data & 0x1;
}

u32 XDig_compensator_Get_params_coef_BaseAddress(XDig_compensator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE);
}

u32 XDig_compensator_Get_params_coef_HighAddress(XDig_compensator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH);
}

u32 XDig_compensator_Get_params_coef_TotalBytes(XDig_compensator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH - XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + 1);
}

u32 XDig_compensator_Get_params_coef_BitWidth(XDig_compensator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDIG_COMPENSATOR_AXILITES_WIDTH_PARAMS_COEF;
}

u32 XDig_compensator_Get_params_coef_Depth(XDig_compensator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDIG_COMPENSATOR_AXILITES_DEPTH_PARAMS_COEF;
}

u32 XDig_compensator_Write_params_coef_Words(XDig_compensator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH - XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XDig_compensator_Read_params_coef_Words(XDig_compensator *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH - XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + (offset + i)*4);
    }
    return length;
}

u32 XDig_compensator_Write_params_coef_Bytes(XDig_compensator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH - XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XDig_compensator_Read_params_coef_Bytes(XDig_compensator *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH - XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE + offset + i);
    }
    return length;
}

