// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of params_vRef
//        bit 31~0 - params_vRef[31:0] (Read/Write)
// 0x14 : reserved
// 0x30 : Data signal of params_y_max
//        bit 31~0 - params_y_max[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of params_adcMask
//        bit 31~0 - params_adcMask[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of yVmeasDbg
//        bit 31~0 - yVmeasDbg[31:0] (Read)
// 0x44 : Control signal of yVmeasDbg
//        bit 0  - yVmeasDbg_ap_vld (Read/COR)
//        others - reserved
// 0x48 : Data signal of yDbg
//        bit 31~0 - yDbg[31:0] (Read)
// 0x4c : Control signal of yDbg
//        bit 0  - yDbg_ap_vld (Read/COR)
//        others - reserved
// 0x50 : Data signal of eDbg
//        bit 31~0 - eDbg[31:0] (Read)
// 0x54 : Control signal of eDbg
//        bit 0  - eDbg_ap_vld (Read/COR)
//        others - reserved
// 0x58 : Data signal of uDbg
//        bit 9~0 - uDbg[9:0] (Read)
//        others  - reserved
// 0x5c : Control signal of uDbg
//        bit 0  - uDbg_ap_vld (Read/COR)
//        others - reserved
// 0x20 ~
// 0x2f : Memory 'params_coef' (3 * 32b)
//        Word n : bit [31:0] - params_coef[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_VREF_DATA    0x10
#define XDIG_COMPENSATOR_AXILITES_BITS_PARAMS_VREF_DATA    32
#define XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_Y_MAX_DATA   0x30
#define XDIG_COMPENSATOR_AXILITES_BITS_PARAMS_Y_MAX_DATA   32
#define XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_ADCMASK_DATA 0x38
#define XDIG_COMPENSATOR_AXILITES_BITS_PARAMS_ADCMASK_DATA 32
#define XDIG_COMPENSATOR_AXILITES_ADDR_YVMEASDBG_DATA      0x40
#define XDIG_COMPENSATOR_AXILITES_BITS_YVMEASDBG_DATA      32
#define XDIG_COMPENSATOR_AXILITES_ADDR_YVMEASDBG_CTRL      0x44
#define XDIG_COMPENSATOR_AXILITES_ADDR_YDBG_DATA           0x48
#define XDIG_COMPENSATOR_AXILITES_BITS_YDBG_DATA           32
#define XDIG_COMPENSATOR_AXILITES_ADDR_YDBG_CTRL           0x4c
#define XDIG_COMPENSATOR_AXILITES_ADDR_EDBG_DATA           0x50
#define XDIG_COMPENSATOR_AXILITES_BITS_EDBG_DATA           32
#define XDIG_COMPENSATOR_AXILITES_ADDR_EDBG_CTRL           0x54
#define XDIG_COMPENSATOR_AXILITES_ADDR_UDBG_DATA           0x58
#define XDIG_COMPENSATOR_AXILITES_BITS_UDBG_DATA           10
#define XDIG_COMPENSATOR_AXILITES_ADDR_UDBG_CTRL           0x5c
#define XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_BASE    0x20
#define XDIG_COMPENSATOR_AXILITES_ADDR_PARAMS_COEF_HIGH    0x2f
#define XDIG_COMPENSATOR_AXILITES_WIDTH_PARAMS_COEF        32
#define XDIG_COMPENSATOR_AXILITES_DEPTH_PARAMS_COEF        3

