# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.cache/wt [current_project]
set_property parent.project_path D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths d:/flyback_controller/ip_repo [current_project]
add_files D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/top_design.bd
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_processing_system7_0_0/top_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_rst_processing_system7_0_100M_1/top_design_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_rst_processing_system7_0_100M_1/top_design_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_rst_processing_system7_0_100M_1/top_design_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_Dig_compensator_0_0/constraints/Dig_compensator_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_xbar_0/top_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/ip/top_design_auto_pc_0/top_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/top_design_ooc.xdc]
set_property is_locked true [get_files D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/top_design.bd]

read_vhdl -library xil_defaultlib D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/sources_1/bd/top_design/hdl/top_design_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/constrs_1/imports/constrs_1/ZYBO_Master.xdc
set_property used_in_implementation false [get_files D:/flyback_controller/flyback_controller_v01/flyback_controller_v01.srcs/constrs_1/imports/constrs_1/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_design_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef top_design_wrapper.dcp

catch { report_utilization -file top_design_wrapper_utilization_synth.rpt -pb top_design_wrapper_utilization_synth.pb }
