// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XPI_COMPENSATOR_DIFFEQ_H
#define XPI_COMPENSATOR_DIFFEQ_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpi_compensator_diffeq_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XPi_compensator_diffeq_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XPi_compensator_diffeq;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPi_compensator_diffeq_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPi_compensator_diffeq_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPi_compensator_diffeq_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPi_compensator_diffeq_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPi_compensator_diffeq_Initialize(XPi_compensator_diffeq *InstancePtr, u16 DeviceId);
XPi_compensator_diffeq_Config* XPi_compensator_diffeq_LookupConfig(u16 DeviceId);
int XPi_compensator_diffeq_CfgInitialize(XPi_compensator_diffeq *InstancePtr, XPi_compensator_diffeq_Config *ConfigPtr);
#else
int XPi_compensator_diffeq_Initialize(XPi_compensator_diffeq *InstancePtr, const char* InstanceName);
int XPi_compensator_diffeq_Release(XPi_compensator_diffeq *InstancePtr);
#endif


void XPi_compensator_diffeq_Set_X_MAX(XPi_compensator_diffeq *InstancePtr, u32 Data);
u32 XPi_compensator_diffeq_Get_X_MAX(XPi_compensator_diffeq *InstancePtr);
void XPi_compensator_diffeq_Set_b0(XPi_compensator_diffeq *InstancePtr, u32 Data);
u32 XPi_compensator_diffeq_Get_b0(XPi_compensator_diffeq *InstancePtr);
void XPi_compensator_diffeq_Set_b1(XPi_compensator_diffeq *InstancePtr, u32 Data);
u32 XPi_compensator_diffeq_Get_b1(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_yVmeasDbg(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_yVmeasDbg_vld(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_yDbg(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_yDbg_vld(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_eDbg(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_eDbg_vld(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_uDbg(XPi_compensator_diffeq *InstancePtr);
u32 XPi_compensator_diffeq_Get_uDbg_vld(XPi_compensator_diffeq *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
