// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpi_compensator_diffeq.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPi_compensator_diffeq_CfgInitialize(XPi_compensator_diffeq *InstancePtr, XPi_compensator_diffeq_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPi_compensator_diffeq_Set_X_MAX(XPi_compensator_diffeq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPi_compensator_diffeq_WriteReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_X_MAX_DATA, Data);
}

u32 XPi_compensator_diffeq_Get_X_MAX(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_X_MAX_DATA);
    return Data;
}

void XPi_compensator_diffeq_Set_b0(XPi_compensator_diffeq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPi_compensator_diffeq_WriteReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_B0_DATA, Data);
}

u32 XPi_compensator_diffeq_Get_b0(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_B0_DATA);
    return Data;
}

void XPi_compensator_diffeq_Set_b1(XPi_compensator_diffeq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPi_compensator_diffeq_WriteReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_B1_DATA, Data);
}

u32 XPi_compensator_diffeq_Get_b1(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_B1_DATA);
    return Data;
}

u32 XPi_compensator_diffeq_Get_yVmeasDbg(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_YVMEASDBG_DATA);
    return Data;
}

u32 XPi_compensator_diffeq_Get_yVmeasDbg_vld(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_YVMEASDBG_CTRL);
    return Data & 0x1;
}

u32 XPi_compensator_diffeq_Get_yDbg(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_YDBG_DATA);
    return Data;
}

u32 XPi_compensator_diffeq_Get_yDbg_vld(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_YDBG_CTRL);
    return Data & 0x1;
}

u32 XPi_compensator_diffeq_Get_eDbg(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_EDBG_DATA);
    return Data;
}

u32 XPi_compensator_diffeq_Get_eDbg_vld(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_EDBG_CTRL);
    return Data & 0x1;
}

u32 XPi_compensator_diffeq_Get_uDbg(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_UDBG_DATA);
    return Data;
}

u32 XPi_compensator_diffeq_Get_uDbg_vld(XPi_compensator_diffeq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPi_compensator_diffeq_ReadReg(InstancePtr->Axilites_BaseAddress, XPI_COMPENSATOR_DIFFEQ_AXILITES_ADDR_UDBG_CTRL);
    return Data & 0x1;
}

