#pragma line 1 "digital_compensator/digital_compensator.c" ::: -10
#pragma line 1 "digital_compensator/digital_compensator.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 283 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 55
#pragma line 421 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 182
#pragma line 8 "<command line>" 2 ::: 184
#pragma line 1 "<built-in>" 2 ::: 185
#pragma line 1 "digital_compensator/digital_compensator.c" 2 ::: 186
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 1 ::: 187
#pragma line 62 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 240
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 241
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 251
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 262
#pragma line 18 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 268
#pragma line 62 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 282
#pragma line 10 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 289
#pragma line 32 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 293
#pragma line 147 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 296
#pragma line 225 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 300
#pragma line 247 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 302
#pragma line 277 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 304
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 305
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 319
#pragma line 674 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 325
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 326
#pragma line 674 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 327
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 329
#pragma line 675 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 330
#pragma line 13 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 331
#pragma line 46 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 351
#pragma line 102 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 353
#pragma line 277 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 355
#pragma line 316 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 359
#pragma line 370 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 365
#pragma line 380 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 367
#pragma line 392 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 369
#pragma line 405 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 371
#pragma line 418 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 373
#pragma line 428 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 375
#pragma line 456 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 386
#pragma line 518 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 406
#pragma line 605 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 420
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 484
#pragma line 36 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 485
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 626
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 636
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 642
#pragma line 175 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 643
#pragma line 63 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 644
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 645
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 655
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 661
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 664
#pragma line 11 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 672
#pragma line 26 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 676
#pragma line 84 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 688
#pragma line 120 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 707
#pragma line 157 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 709
#pragma line 312 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 855
#pragma line 330 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 863
#pragma line 373 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 899
#pragma line 417 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 934
#pragma line 475 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 964
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1000
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1010
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1016
#pragma line 509 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1017
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1020
#pragma line 511 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1028
#pragma line 64 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 1029
#pragma line 77 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 1030
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1031
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1089
#pragma line 97 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1143
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1144
#pragma line 98 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2183
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2184
#pragma line 99 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3211
#pragma line 108 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3212
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3213
#pragma line 109 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4252
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4253
#pragma line 110 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5280
#pragma line 131 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5281
#pragma line 147 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5284
#pragma line 58 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5286
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5287
#pragma line 98 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5340
#pragma line 108 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5342
#pragma line 129 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5344
#pragma line 143 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5349
#pragma line 156 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5352
#pragma line 192 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5354
#pragma line 358 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5356
#pragma line 59 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5358
#pragma line 85 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 5359
#pragma line 114 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 5361
#pragma line 78 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 5363
#pragma line 88 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 5364
#pragma line 2 "digital_compensator/digital_compensator.c" 2 ::: 5366
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5386
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5389
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5392
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5395
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5398
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5401
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5404
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5407
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5410
#pragma line 19 "digital_compensator/digital_compensator.c" ::: 5413
