lappend pragmaStatus0 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "digital_compensator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'digital_compensator' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "INTERFACE" source "D:/flyback_controller/hls/digital_compensator/digital_compensator.c" location "Dig_compensator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
