// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Dig_compensator,hls_ip_2015_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.613500,HLS_SYN_LAT=103,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=16,HLS_SYN_FF=2149,HLS_SYN_LUT=3732}" *)

module Dig_compensator (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        params_vRef,
        params_a_0,
        params_a_1,
        params_a_2,
        params_a_3,
        params_b_0,
        params_b_1,
        params_b_2,
        params_b_3,
        v_meas,
        u
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 52'b1;
parameter    ap_ST_st2_fsm_1 = 52'b10;
parameter    ap_ST_st3_fsm_2 = 52'b100;
parameter    ap_ST_st4_fsm_3 = 52'b1000;
parameter    ap_ST_st5_fsm_4 = 52'b10000;
parameter    ap_ST_st6_fsm_5 = 52'b100000;
parameter    ap_ST_st7_fsm_6 = 52'b1000000;
parameter    ap_ST_st8_fsm_7 = 52'b10000000;
parameter    ap_ST_st9_fsm_8 = 52'b100000000;
parameter    ap_ST_st10_fsm_9 = 52'b1000000000;
parameter    ap_ST_st11_fsm_10 = 52'b10000000000;
parameter    ap_ST_st12_fsm_11 = 52'b100000000000;
parameter    ap_ST_st13_fsm_12 = 52'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 52'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 52'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 52'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 52'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 52'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 52'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 52'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 52'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 52'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 52'b10000000000000000000000;
parameter    ap_ST_st24_fsm_23 = 52'b100000000000000000000000;
parameter    ap_ST_st25_fsm_24 = 52'b1000000000000000000000000;
parameter    ap_ST_st26_fsm_25 = 52'b10000000000000000000000000;
parameter    ap_ST_st27_fsm_26 = 52'b100000000000000000000000000;
parameter    ap_ST_st28_fsm_27 = 52'b1000000000000000000000000000;
parameter    ap_ST_st29_fsm_28 = 52'b10000000000000000000000000000;
parameter    ap_ST_st30_fsm_29 = 52'b100000000000000000000000000000;
parameter    ap_ST_st31_fsm_30 = 52'b1000000000000000000000000000000;
parameter    ap_ST_st32_fsm_31 = 52'b10000000000000000000000000000000;
parameter    ap_ST_st33_fsm_32 = 52'b100000000000000000000000000000000;
parameter    ap_ST_st34_fsm_33 = 52'b1000000000000000000000000000000000;
parameter    ap_ST_st35_fsm_34 = 52'b10000000000000000000000000000000000;
parameter    ap_ST_st36_fsm_35 = 52'b100000000000000000000000000000000000;
parameter    ap_ST_st37_fsm_36 = 52'b1000000000000000000000000000000000000;
parameter    ap_ST_st38_fsm_37 = 52'b10000000000000000000000000000000000000;
parameter    ap_ST_st39_fsm_38 = 52'b100000000000000000000000000000000000000;
parameter    ap_ST_st40_fsm_39 = 52'b1000000000000000000000000000000000000000;
parameter    ap_ST_st41_fsm_40 = 52'b10000000000000000000000000000000000000000;
parameter    ap_ST_st42_fsm_41 = 52'b100000000000000000000000000000000000000000;
parameter    ap_ST_st43_fsm_42 = 52'b1000000000000000000000000000000000000000000;
parameter    ap_ST_st44_fsm_43 = 52'b10000000000000000000000000000000000000000000;
parameter    ap_ST_st45_fsm_44 = 52'b100000000000000000000000000000000000000000000;
parameter    ap_ST_st46_fsm_45 = 52'b1000000000000000000000000000000000000000000000;
parameter    ap_ST_st47_fsm_46 = 52'b10000000000000000000000000000000000000000000000;
parameter    ap_ST_st48_fsm_47 = 52'b100000000000000000000000000000000000000000000000;
parameter    ap_ST_st49_fsm_48 = 52'b1000000000000000000000000000000000000000000000000;
parameter    ap_ST_st50_fsm_49 = 52'b10000000000000000000000000000000000000000000000000;
parameter    ap_ST_st51_fsm_50 = 52'b100000000000000000000000000000000000000000000000000;
parameter    ap_ST_st52_fsm_51 = 52'b1000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv32_25 = 32'b100101;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_2E = 32'b101110;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv32_2A = 32'b101010;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_31 = 32'b110001;
parameter    ap_const_lv32_32 = 32'b110010;
parameter    ap_const_lv32_33 = 32'b110011;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_44480000 = 32'b1000100010010000000000000000000;
parameter    ap_const_lv64_400A666666666666 = 64'b100000000001010011001100110011001100110011001100110011001100110;
parameter    ap_const_lv64_3F30000000000000 = 64'b11111100110000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv23_0 = 23'b00000000000000000000000;
parameter    ap_const_lv9_181 = 9'b110000001;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv8_7F = 8'b1111111;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv5_4 = 5'b100;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] params_vRef;
input  [31:0] params_a_0;
input  [31:0] params_a_1;
input  [31:0] params_a_2;
input  [31:0] params_a_3;
input  [31:0] params_b_0;
input  [31:0] params_b_1;
input  [31:0] params_b_2;
input  [31:0] params_b_3;
input  [11:0] v_meas;
output  [9:0] u;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] u;
(* fsm_encoding = "none" *) reg   [51:0] ap_CS_fsm = 52'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_68;
reg   [31:0] y_3 = 32'b00000000000000000000000000000000;
reg   [31:0] y_1 = 32'b00000000000000000000000000000000;
reg   [31:0] y_2 = 32'b00000000000000000000000000000000;
reg   [31:0] e_1 = 32'b00000000000000000000000000000000;
reg   [31:0] e_2 = 32'b00000000000000000000000000000000;
reg   [31:0] e_3 = 32'b00000000000000000000000000000000;
wire   [63:0] grp_fu_261_p2;
reg   [63:0] reg_278;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_99;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_106;
wire   [31:0] grp_fu_248_p2;
reg   [31:0] reg_284;
reg    ap_sig_cseq_ST_st28_fsm_27;
reg    ap_sig_bdd_116;
reg    ap_sig_cseq_ST_st38_fsm_37;
reg    ap_sig_bdd_123;
wire   [31:0] grp_fu_240_p2;
reg   [31:0] reg_289;
reg    ap_sig_cseq_ST_st33_fsm_32;
reg    ap_sig_bdd_133;
reg    ap_sig_cseq_ST_st47_fsm_46;
reg    ap_sig_bdd_140;
wire   [63:0] grp_fu_267_p1;
reg   [63:0] tmp_1_reg_747;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_155;
wire   [31:0] v_measReal_fu_252_p1;
reg   [31:0] v_measReal_reg_752;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_164;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_bdd_173;
reg    ap_sig_cseq_ST_st24_fsm_23;
reg    ap_sig_bdd_182;
reg   [31:0] e_reg_797;
wire   [2:0] i_3_fu_306_p2;
reg   [2:0] i_3_reg_806;
reg    ap_sig_cseq_ST_st25_fsm_24;
reg    ap_sig_bdd_204;
wire   [31:0] tmp_fu_316_p6;
wire   [0:0] exitcond1_fu_300_p2;
wire   [31:0] tmp_4_fu_331_p6;
reg   [31:0] y_3_load_reg_821;
reg   [31:0] y_1_load_reg_826;
reg   [31:0] y_2_load_reg_832;
wire   [31:0] params_a_load_phi_fu_385_p3;
reg   [31:0] params_a_load_phi_reg_841;
reg    ap_sig_cseq_ST_st34_fsm_33;
reg    ap_sig_bdd_229;
wire   [0:0] exitcond_fu_357_p2;
wire   [31:0] y_load_phi_fu_398_p3;
reg   [31:0] y_load_phi_reg_846;
wire   [2:0] i_4_fu_405_p2;
reg   [2:0] i_4_reg_851;
reg    ap_sig_cseq_ST_st43_fsm_42;
reg    ap_sig_bdd_244;
wire   [0:0] grp_fu_255_p2;
reg   [0:0] tmp_11_reg_875;
reg    ap_sig_cseq_ST_st48_fsm_47;
reg    ap_sig_bdd_253;
wire   [31:0] tmp_9_fu_460_p3;
reg   [31:0] tmp_9_reg_880;
reg    ap_sig_cseq_ST_st49_fsm_48;
reg    ap_sig_bdd_262;
wire   [0:0] tmp_19_fu_503_p2;
reg   [0:0] tmp_19_reg_887;
reg    ap_sig_cseq_ST_st50_fsm_49;
reg    ap_sig_bdd_271;
wire   [31:0] x_assign_fu_509_p3;
reg   [31:0] x_assign_reg_892;
reg    ap_sig_cseq_ST_st51_fsm_50;
reg    ap_sig_bdd_280;
wire   [1:0] i_5_fu_642_p2;
reg    ap_sig_cseq_ST_st52_fsm_51;
reg    ap_sig_bdd_289;
wire   [0:0] tmp_13_fu_636_p2;
reg   [2:0] i_reg_183;
reg   [31:0] num_reg_194;
reg   [2:0] i_1_reg_206;
reg   [31:0] den_reg_217;
wire   [1:0] i_2_phi_fu_233_p4;
reg   [1:0] i_2_reg_229;
wire   [31:0] y_load_1_phi_fu_707_p3;
wire   [31:0] e_load_1_phi_fu_668_p3;
reg   [31:0] y_2_load_1_fu_114;
reg   [31:0] y_1_load_1_fu_118;
wire   [9:0] tmp_23_fu_627_p3;
reg   [9:0] u_preg = 10'b0000000000;
reg   [31:0] grp_fu_240_p0;
reg   [31:0] grp_fu_240_p1;
reg    ap_sig_cseq_ST_st29_fsm_28;
reg    ap_sig_bdd_356;
reg    ap_sig_cseq_ST_st39_fsm_38;
reg    ap_sig_bdd_364;
reg   [31:0] grp_fu_248_p0;
reg   [31:0] grp_fu_248_p1;
reg    ap_sig_cseq_ST_st35_fsm_34;
reg    ap_sig_bdd_374;
reg   [31:0] grp_fu_255_p0;
reg   [31:0] grp_fu_255_p1;
reg   [63:0] grp_fu_261_p0;
reg   [63:0] grp_fu_261_p1;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_389;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_396;
wire   [31:0] grp_fu_267_p0;
wire   [1:0] tmp_8_fu_312_p1;
wire   [1:0] tmp_27_fu_363_p1;
wire   [0:0] sel_tmp_fu_367_p2;
wire   [0:0] sel_tmp2_fu_379_p2;
wire   [31:0] sel_tmp1_fu_373_p3;
wire   [31:0] sel_tmp5_fu_392_p3;
wire   [31:0] tmp_7_to_int_fu_419_p1;
wire   [7:0] tmp_5_fu_423_p4;
wire   [22:0] tmp_16_fu_433_p1;
wire   [0:0] notrhs_fu_443_p2;
wire   [0:0] notlhs_fu_437_p2;
wire   [0:0] tmp_10_fu_449_p2;
wire   [0:0] tmp_12_fu_455_p2;
wire   [31:0] tmp_9_to_int_fu_468_p1;
wire   [7:0] tmp_15_fu_471_p4;
wire   [22:0] tmp_20_fu_481_p1;
wire   [0:0] notrhs1_fu_491_p2;
wire   [0:0] notlhs1_fu_485_p2;
wire   [0:0] tmp_17_fu_497_p2;
wire   [31:0] p_Val2_s_fu_515_p1;
wire   [22:0] loc_V_1_fu_529_p1;
wire   [23:0] p_Result_s_fu_533_p3;
wire   [7:0] loc_V_fu_519_p4;
wire   [8:0] tmp_i_i_i_cast_fu_545_p1;
wire   [8:0] sh_assign_fu_549_p2;
wire   [7:0] tmp_4_i_i_fu_563_p2;
wire   [0:0] isNeg_fu_555_p3;
wire  signed [8:0] tmp_4_i_i_cast_fu_569_p1;
wire   [8:0] sh_assign_1_fu_573_p3;
wire  signed [31:0] sh_assign_1_cast_fu_581_p1;
wire  signed [23:0] sh_assign_1_cast_cast_fu_585_p1;
wire   [61:0] tmp_2_i_i_fu_541_p1;
wire   [61:0] tmp_6_i_i_fu_589_p1;
wire   [23:0] tmp_7_i_i_fu_593_p2;
wire   [0:0] tmp_26_fu_605_p3;
wire   [61:0] tmp_9_i_i_fu_599_p2;
wire   [9:0] tmp_21_fu_613_p1;
wire   [9:0] tmp_22_fu_617_p4;
wire   [0:0] sel_tmp9_fu_648_p2;
wire   [0:0] sel_tmp4_fu_662_p2;
wire   [31:0] sel_tmp3_fu_654_p3;
wire   [31:0] sel_tmp6_fu_699_p3;
reg   [1:0] grp_fu_240_opcode;
wire    grp_fu_240_ce;
wire    grp_fu_248_ce;
reg   [4:0] grp_fu_255_opcode;
wire    grp_fu_261_ce;
wire    grp_fu_267_ce;
reg   [51:0] ap_NS_fsm;


Dig_compensator_faddfsub_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Dig_compensator_faddfsub_32ns_32ns_32_5_full_dsp_U0(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_240_p0 ),
    .din1( grp_fu_240_p1 ),
    .opcode( grp_fu_240_opcode ),
    .ce( grp_fu_240_ce ),
    .dout( grp_fu_240_p2 )
);

Dig_compensator_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Dig_compensator_fmul_32ns_32ns_32_4_max_dsp_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_248_p0 ),
    .din1( grp_fu_248_p1 ),
    .ce( grp_fu_248_ce ),
    .dout( grp_fu_248_p2 )
);

Dig_compensator_fptrunc_64ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
Dig_compensator_fptrunc_64ns_32_1_U2(
    .din0( reg_278 ),
    .dout( v_measReal_fu_252_p1 )
);

Dig_compensator_fcmp_32ns_32ns_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
Dig_compensator_fcmp_32ns_32ns_1_1_U3(
    .din0( grp_fu_255_p0 ),
    .din1( grp_fu_255_p1 ),
    .opcode( grp_fu_255_opcode ),
    .dout( grp_fu_255_p2 )
);

Dig_compensator_dmul_64ns_64ns_64_6_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
Dig_compensator_dmul_64ns_64ns_64_6_max_dsp_U4(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_261_p0 ),
    .din1( grp_fu_261_p1 ),
    .ce( grp_fu_261_ce ),
    .dout( grp_fu_261_p2 )
);

Dig_compensator_sitodp_32ns_64_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Dig_compensator_sitodp_32ns_64_6_U5(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_267_p0 ),
    .ce( grp_fu_267_ce ),
    .dout( grp_fu_267_p1 )
);

Dig_compensator_mux_4to1_sel2_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
Dig_compensator_mux_4to1_sel2_32_1_U6(
    .din1( params_b_0 ),
    .din2( params_b_1 ),
    .din3( params_b_2 ),
    .din4( params_b_3 ),
    .din5( tmp_8_fu_312_p1 ),
    .dout( tmp_fu_316_p6 )
);

Dig_compensator_mux_4to1_sel2_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
Dig_compensator_mux_4to1_sel2_32_1_U7(
    .din1( e_reg_797 ),
    .din2( e_1 ),
    .din3( e_2 ),
    .din4( e_3 ),
    .din5( tmp_8_fu_312_p1 ),
    .dout( tmp_4_fu_331_p6 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_u_preg
    if (ap_rst == 1'b1) begin
        u_preg <= ap_const_lv10_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st51_fsm_50)) begin
            u_preg <= tmp_23_fu_627_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24) & ~(exitcond1_fu_300_p2 == ap_const_lv1_0))) begin
        den_reg_217 <= ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42)) begin
        den_reg_217 <= grp_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24) & ~(exitcond1_fu_300_p2 == ap_const_lv1_0))) begin
        i_1_reg_206 <= ap_const_lv3_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st43_fsm_42)) begin
        i_1_reg_206 <= i_4_reg_851;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & (ap_const_lv1_0 == tmp_13_fu_636_p2))) begin
        i_2_reg_229 <= i_5_fu_642_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st51_fsm_50)) begin
        i_2_reg_229 <= ap_const_lv2_3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st33_fsm_32)) begin
        i_reg_183 <= i_3_reg_806;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23)) begin
        i_reg_183 <= ap_const_lv3_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st33_fsm_32)) begin
        num_reg_194 <= grp_fu_240_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23)) begin
        num_reg_194 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & (ap_const_lv1_0 == tmp_13_fu_636_p2) & (i_2_phi_fu_233_p4 == ap_const_lv2_1))) begin
        y_1_load_1_fu_118 <= y_load_1_phi_fu_707_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~(ap_const_lv1_0 == exitcond_fu_357_p2))) begin
        y_1_load_1_fu_118 <= y_1_load_reg_826;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & (ap_const_lv1_0 == tmp_13_fu_636_p2) & (i_2_phi_fu_233_p4 == ap_const_lv2_2))) begin
        y_2_load_1_fu_114 <= y_load_1_phi_fu_707_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~(ap_const_lv1_0 == exitcond_fu_357_p2))) begin
        y_2_load_1_fu_114 <= y_2_load_reg_832;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & (ap_const_lv1_0 == tmp_13_fu_636_p2) & (i_2_phi_fu_233_p4 == ap_const_lv2_1))) begin
        e_1 <= e_load_1_phi_fu_668_p3;
        y_1 <= y_load_1_phi_fu_707_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & (ap_const_lv1_0 == tmp_13_fu_636_p2) & (i_2_phi_fu_233_p4 == ap_const_lv2_2))) begin
        e_2 <= e_load_1_phi_fu_668_p3;
        y_2 <= y_load_1_phi_fu_707_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & (ap_const_lv1_0 == tmp_13_fu_636_p2) & ~(i_2_phi_fu_233_p4 == ap_const_lv2_2) & ~(i_2_phi_fu_233_p4 == ap_const_lv2_1))) begin
        e_3 <= e_load_1_phi_fu_668_p3;
        y_3 <= y_load_1_phi_fu_707_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23)) begin
        e_reg_797 <= grp_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24)) begin
        i_3_reg_806 <= i_3_fu_306_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & (ap_const_lv1_0 == exitcond_fu_357_p2))) begin
        i_4_reg_851 <= i_4_fu_405_p2;
        params_a_load_phi_reg_841 <= params_a_load_phi_fu_385_p3;
        y_load_phi_reg_846 <= y_load_phi_fu_398_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        reg_278 <= grp_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27) | (ap_const_logic_1 == ap_sig_cseq_ST_st38_fsm_37))) begin
        reg_284 <= grp_fu_248_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st33_fsm_32) | (ap_const_logic_1 == ap_sig_cseq_ST_st47_fsm_46))) begin
        reg_289 <= grp_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st48_fsm_47)) begin
        tmp_11_reg_875 <= grp_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st50_fsm_49)) begin
        tmp_19_reg_887 <= tmp_19_fu_503_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        tmp_1_reg_747 <= grp_fu_267_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st49_fsm_48)) begin
        tmp_9_reg_880 <= tmp_9_fu_460_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        v_measReal_reg_752 <= v_measReal_fu_252_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st51_fsm_50)) begin
        x_assign_reg_892 <= x_assign_fu_509_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24) & ~(exitcond1_fu_300_p2 == ap_const_lv1_0))) begin
        y_1_load_reg_826 <= y_1;
        y_2_load_reg_832 <= y_2;
        y_3_load_reg_821 <= y_3;
    end
end

always @ (ap_sig_cseq_ST_st52_fsm_51 or tmp_13_fu_636_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & ~(ap_const_lv1_0 == tmp_13_fu_636_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st52_fsm_51 or tmp_13_fu_636_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st52_fsm_51) & ~(ap_const_lv1_0 == tmp_13_fu_636_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_99) begin
    if (ap_sig_bdd_99) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_396) begin
    if (ap_sig_bdd_396) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_106) begin
    if (ap_sig_bdd_106) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_164) begin
    if (ap_sig_bdd_164) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_68) begin
    if (ap_sig_bdd_68) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_173) begin
    if (ap_sig_bdd_173) begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_182) begin
    if (ap_sig_bdd_182) begin
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_204) begin
    if (ap_sig_bdd_204) begin
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_116) begin
    if (ap_sig_bdd_116) begin
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_356) begin
    if (ap_sig_bdd_356) begin
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_133) begin
    if (ap_sig_bdd_133) begin
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_229) begin
    if (ap_sig_bdd_229) begin
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_374) begin
    if (ap_sig_bdd_374) begin
        ap_sig_cseq_ST_st35_fsm_34 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st35_fsm_34 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_123) begin
    if (ap_sig_bdd_123) begin
        ap_sig_cseq_ST_st38_fsm_37 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st38_fsm_37 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_364) begin
    if (ap_sig_bdd_364) begin
        ap_sig_cseq_ST_st39_fsm_38 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st39_fsm_38 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_244) begin
    if (ap_sig_bdd_244) begin
        ap_sig_cseq_ST_st43_fsm_42 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st43_fsm_42 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_140) begin
    if (ap_sig_bdd_140) begin
        ap_sig_cseq_ST_st47_fsm_46 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st47_fsm_46 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_253) begin
    if (ap_sig_bdd_253) begin
        ap_sig_cseq_ST_st48_fsm_47 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st48_fsm_47 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_262) begin
    if (ap_sig_bdd_262) begin
        ap_sig_cseq_ST_st49_fsm_48 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st49_fsm_48 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_271) begin
    if (ap_sig_bdd_271) begin
        ap_sig_cseq_ST_st50_fsm_49 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st50_fsm_49 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_280) begin
    if (ap_sig_bdd_280) begin
        ap_sig_cseq_ST_st51_fsm_50 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st51_fsm_50 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_289) begin
    if (ap_sig_bdd_289) begin
        ap_sig_cseq_ST_st52_fsm_51 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st52_fsm_51 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_155) begin
    if (ap_sig_bdd_155) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_389) begin
    if (ap_sig_bdd_389) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st20_fsm_19 or ap_sig_cseq_ST_st34_fsm_33 or exitcond_fu_357_p2 or ap_sig_cseq_ST_st29_fsm_28 or ap_sig_cseq_ST_st39_fsm_38) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) | ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) & ~(ap_const_lv1_0 == exitcond_fu_357_p2)))) begin
        grp_fu_240_opcode = ap_const_lv2_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28) | (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_38))) begin
        grp_fu_240_opcode = ap_const_lv2_0;
    end else begin
        grp_fu_240_opcode = 'bx;
    end
end

always @ (params_vRef or ap_sig_cseq_ST_st20_fsm_19 or ap_sig_cseq_ST_st34_fsm_33 or num_reg_194 or den_reg_217 or ap_sig_cseq_ST_st29_fsm_28 or ap_sig_cseq_ST_st39_fsm_38) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_38)) begin
        grp_fu_240_p0 = den_reg_217;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33) | (ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28))) begin
        grp_fu_240_p0 = num_reg_194;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        grp_fu_240_p0 = params_vRef;
    end else begin
        grp_fu_240_p0 = 'bx;
    end
end

always @ (reg_284 or v_measReal_reg_752 or ap_sig_cseq_ST_st20_fsm_19 or ap_sig_cseq_ST_st34_fsm_33 or den_reg_217 or ap_sig_cseq_ST_st29_fsm_28 or ap_sig_cseq_ST_st39_fsm_38) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        grp_fu_240_p1 = den_reg_217;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28) | (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_38))) begin
        grp_fu_240_p1 = reg_284;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        grp_fu_240_p1 = v_measReal_reg_752;
    end else begin
        grp_fu_240_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st25_fsm_24 or tmp_fu_316_p6 or params_a_load_phi_reg_841 or ap_sig_cseq_ST_st35_fsm_34) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st35_fsm_34)) begin
        grp_fu_248_p0 = params_a_load_phi_reg_841;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24)) begin
        grp_fu_248_p0 = tmp_fu_316_p6;
    end else begin
        grp_fu_248_p0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st25_fsm_24 or tmp_4_fu_331_p6 or y_load_phi_reg_846 or ap_sig_cseq_ST_st35_fsm_34) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st35_fsm_34)) begin
        grp_fu_248_p1 = y_load_phi_reg_846;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24)) begin
        grp_fu_248_p1 = tmp_4_fu_331_p6;
    end else begin
        grp_fu_248_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st48_fsm_47 or ap_sig_cseq_ST_st50_fsm_49) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st50_fsm_49)) begin
        grp_fu_255_opcode = ap_const_lv5_4;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st48_fsm_47)) begin
        grp_fu_255_opcode = ap_const_lv5_2;
    end else begin
        grp_fu_255_opcode = 'bx;
    end
end

always @ (reg_289 or ap_sig_cseq_ST_st48_fsm_47 or tmp_9_reg_880 or ap_sig_cseq_ST_st50_fsm_49) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st50_fsm_49)) begin
        grp_fu_255_p0 = tmp_9_reg_880;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st48_fsm_47)) begin
        grp_fu_255_p0 = reg_289;
    end else begin
        grp_fu_255_p0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st48_fsm_47 or ap_sig_cseq_ST_st50_fsm_49) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st50_fsm_49)) begin
        grp_fu_255_p1 = ap_const_lv32_44480000;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st48_fsm_47)) begin
        grp_fu_255_p1 = ap_const_lv32_0;
    end else begin
        grp_fu_255_p1 = 'bx;
    end
end

always @ (reg_278 or tmp_1_reg_747 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st13_fsm_12) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_261_p0 = reg_278;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        grp_fu_261_p0 = tmp_1_reg_747;
    end else begin
        grp_fu_261_p0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st13_fsm_12) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        grp_fu_261_p1 = ap_const_lv64_3F30000000000000;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        grp_fu_261_p1 = ap_const_lv64_400A666666666666;
    end else begin
        grp_fu_261_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st51_fsm_50 or tmp_23_fu_627_p3 or u_preg) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st51_fsm_50)) begin
        u = tmp_23_fu_627_p3;
    end else begin
        u = u_preg;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond1_fu_300_p2 or exitcond_fu_357_p2 or tmp_13_fu_636_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : 
        begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st21_fsm_20;
        end
        ap_ST_st21_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_st22_fsm_21;
        end
        ap_ST_st22_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st23_fsm_22;
        end
        ap_ST_st23_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_st24_fsm_23;
        end
        ap_ST_st24_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_st25_fsm_24;
        end
        ap_ST_st25_fsm_24 : 
        begin
            if (~(exitcond1_fu_300_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end else begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end
        end
        ap_ST_st26_fsm_25 : 
        begin
            ap_NS_fsm = ap_ST_st27_fsm_26;
        end
        ap_ST_st27_fsm_26 : 
        begin
            ap_NS_fsm = ap_ST_st28_fsm_27;
        end
        ap_ST_st28_fsm_27 : 
        begin
            ap_NS_fsm = ap_ST_st29_fsm_28;
        end
        ap_ST_st29_fsm_28 : 
        begin
            ap_NS_fsm = ap_ST_st30_fsm_29;
        end
        ap_ST_st30_fsm_29 : 
        begin
            ap_NS_fsm = ap_ST_st31_fsm_30;
        end
        ap_ST_st31_fsm_30 : 
        begin
            ap_NS_fsm = ap_ST_st32_fsm_31;
        end
        ap_ST_st32_fsm_31 : 
        begin
            ap_NS_fsm = ap_ST_st33_fsm_32;
        end
        ap_ST_st33_fsm_32 : 
        begin
            ap_NS_fsm = ap_ST_st25_fsm_24;
        end
        ap_ST_st34_fsm_33 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_fu_357_p2)) begin
                ap_NS_fsm = ap_ST_st44_fsm_43;
            end else begin
                ap_NS_fsm = ap_ST_st35_fsm_34;
            end
        end
        ap_ST_st35_fsm_34 : 
        begin
            ap_NS_fsm = ap_ST_st36_fsm_35;
        end
        ap_ST_st36_fsm_35 : 
        begin
            ap_NS_fsm = ap_ST_st37_fsm_36;
        end
        ap_ST_st37_fsm_36 : 
        begin
            ap_NS_fsm = ap_ST_st38_fsm_37;
        end
        ap_ST_st38_fsm_37 : 
        begin
            ap_NS_fsm = ap_ST_st39_fsm_38;
        end
        ap_ST_st39_fsm_38 : 
        begin
            ap_NS_fsm = ap_ST_st40_fsm_39;
        end
        ap_ST_st40_fsm_39 : 
        begin
            ap_NS_fsm = ap_ST_st41_fsm_40;
        end
        ap_ST_st41_fsm_40 : 
        begin
            ap_NS_fsm = ap_ST_st42_fsm_41;
        end
        ap_ST_st42_fsm_41 : 
        begin
            ap_NS_fsm = ap_ST_st43_fsm_42;
        end
        ap_ST_st43_fsm_42 : 
        begin
            ap_NS_fsm = ap_ST_st34_fsm_33;
        end
        ap_ST_st44_fsm_43 : 
        begin
            ap_NS_fsm = ap_ST_st45_fsm_44;
        end
        ap_ST_st45_fsm_44 : 
        begin
            ap_NS_fsm = ap_ST_st46_fsm_45;
        end
        ap_ST_st46_fsm_45 : 
        begin
            ap_NS_fsm = ap_ST_st47_fsm_46;
        end
        ap_ST_st47_fsm_46 : 
        begin
            ap_NS_fsm = ap_ST_st48_fsm_47;
        end
        ap_ST_st48_fsm_47 : 
        begin
            ap_NS_fsm = ap_ST_st49_fsm_48;
        end
        ap_ST_st49_fsm_48 : 
        begin
            ap_NS_fsm = ap_ST_st50_fsm_49;
        end
        ap_ST_st50_fsm_49 : 
        begin
            ap_NS_fsm = ap_ST_st51_fsm_50;
        end
        ap_ST_st51_fsm_50 : 
        begin
            ap_NS_fsm = ap_ST_st52_fsm_51;
        end
        ap_ST_st52_fsm_51 : 
        begin
            if (~(ap_const_lv1_0 == tmp_13_fu_636_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st52_fsm_51;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_106 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_116 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_123 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_25]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_133 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_20]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_140 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2E]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_155 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_164 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_173 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_182 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_17]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_204 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_18]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_229 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_21]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_244 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_253 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_262 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_30]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_271 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_31]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_280 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_32]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_289 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_33]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_356 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_364 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_26]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_374 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_22]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_389 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_396 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_68 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_99 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

assign e_load_1_phi_fu_668_p3 = ((sel_tmp4_fu_662_p2[0:0] === 1'b1) ? e_reg_797 : sel_tmp3_fu_654_p3);

assign exitcond1_fu_300_p2 = (i_reg_183 == ap_const_lv3_4? 1'b1: 1'b0);

assign exitcond_fu_357_p2 = (i_1_reg_206 == ap_const_lv3_4? 1'b1: 1'b0);

assign grp_fu_240_ce = ap_const_logic_1;

assign grp_fu_248_ce = ap_const_logic_1;

assign grp_fu_261_ce = ap_const_logic_1;

assign grp_fu_267_ce = ap_const_logic_1;

assign grp_fu_267_p0 = v_meas;

assign i_2_phi_fu_233_p4 = i_2_reg_229;

assign i_3_fu_306_p2 = (i_reg_183 + ap_const_lv3_1);

assign i_4_fu_405_p2 = (ap_const_lv3_1 + i_1_reg_206);

assign i_5_fu_642_p2 = ($signed(i_2_reg_229) + $signed(ap_const_lv2_3));

assign isNeg_fu_555_p3 = sh_assign_fu_549_p2[ap_const_lv32_8];

assign loc_V_1_fu_529_p1 = p_Val2_s_fu_515_p1[22:0];

assign loc_V_fu_519_p4 = {{p_Val2_s_fu_515_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign notlhs1_fu_485_p2 = (tmp_15_fu_471_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notlhs_fu_437_p2 = (tmp_5_fu_423_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notrhs1_fu_491_p2 = (tmp_20_fu_481_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign notrhs_fu_443_p2 = (tmp_16_fu_433_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign p_Result_s_fu_533_p3 = {{ap_const_lv1_1}, {loc_V_1_fu_529_p1}};

assign p_Val2_s_fu_515_p1 = x_assign_fu_509_p3;

assign params_a_load_phi_fu_385_p3 = ((sel_tmp2_fu_379_p2[0:0] === 1'b1) ? params_a_1 : sel_tmp1_fu_373_p3);

assign sel_tmp1_fu_373_p3 = ((sel_tmp_fu_367_p2[0:0] === 1'b1) ? params_a_2 : params_a_3);

assign sel_tmp2_fu_379_p2 = (tmp_27_fu_363_p1 == ap_const_lv2_1? 1'b1: 1'b0);

assign sel_tmp3_fu_654_p3 = ((sel_tmp9_fu_648_p2[0:0] === 1'b1) ? e_1 : e_2);

assign sel_tmp4_fu_662_p2 = (i_5_fu_642_p2 == ap_const_lv2_0? 1'b1: 1'b0);

assign sel_tmp5_fu_392_p3 = ((sel_tmp_fu_367_p2[0:0] === 1'b1) ? y_2_load_reg_832 : y_3_load_reg_821);

assign sel_tmp6_fu_699_p3 = ((sel_tmp9_fu_648_p2[0:0] === 1'b1) ? y_1_load_1_fu_118 : y_2_load_1_fu_114);

assign sel_tmp9_fu_648_p2 = (i_5_fu_642_p2 == ap_const_lv2_1? 1'b1: 1'b0);

assign sel_tmp_fu_367_p2 = (tmp_27_fu_363_p1 == ap_const_lv2_2? 1'b1: 1'b0);

assign sh_assign_1_cast_cast_fu_585_p1 = $signed(sh_assign_1_fu_573_p3);

assign sh_assign_1_cast_fu_581_p1 = $signed(sh_assign_1_fu_573_p3);

assign sh_assign_1_fu_573_p3 = ((isNeg_fu_555_p3[0:0] === 1'b1) ? tmp_4_i_i_cast_fu_569_p1 : sh_assign_fu_549_p2);

assign sh_assign_fu_549_p2 = ($signed(ap_const_lv9_181) + $signed(tmp_i_i_i_cast_fu_545_p1));

assign tmp_10_fu_449_p2 = (notrhs_fu_443_p2 | notlhs_fu_437_p2);

assign tmp_12_fu_455_p2 = (tmp_10_fu_449_p2 & tmp_11_reg_875);

assign tmp_13_fu_636_p2 = (i_2_reg_229 == ap_const_lv2_0? 1'b1: 1'b0);

assign tmp_15_fu_471_p4 = {{tmp_9_to_int_fu_468_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_16_fu_433_p1 = tmp_7_to_int_fu_419_p1[22:0];

assign tmp_17_fu_497_p2 = (notrhs1_fu_491_p2 | notlhs1_fu_485_p2);

assign tmp_19_fu_503_p2 = (tmp_17_fu_497_p2 & grp_fu_255_p2);

assign tmp_20_fu_481_p1 = tmp_9_to_int_fu_468_p1[22:0];

assign tmp_21_fu_613_p1 = tmp_26_fu_605_p3;

assign tmp_22_fu_617_p4 = {{tmp_9_i_i_fu_599_p2[ap_const_lv32_20 : ap_const_lv32_17]}};

assign tmp_23_fu_627_p3 = ((isNeg_fu_555_p3[0:0] === 1'b1) ? tmp_21_fu_613_p1 : tmp_22_fu_617_p4);

assign tmp_26_fu_605_p3 = tmp_7_i_i_fu_593_p2[ap_const_lv32_17];

assign tmp_27_fu_363_p1 = i_1_reg_206[1:0];

assign tmp_2_i_i_fu_541_p1 = p_Result_s_fu_533_p3;

assign tmp_4_i_i_cast_fu_569_p1 = $signed(tmp_4_i_i_fu_563_p2);

assign tmp_4_i_i_fu_563_p2 = (ap_const_lv8_7F - loc_V_fu_519_p4);

assign tmp_5_fu_423_p4 = {{tmp_7_to_int_fu_419_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_6_i_i_fu_589_p1 = $unsigned(sh_assign_1_cast_fu_581_p1);

assign tmp_7_i_i_fu_593_p2 = p_Result_s_fu_533_p3 >> sh_assign_1_cast_cast_fu_585_p1;

assign tmp_7_to_int_fu_419_p1 = reg_289;

assign tmp_8_fu_312_p1 = i_reg_183[1:0];

assign tmp_9_fu_460_p3 = ((tmp_12_fu_455_p2[0:0] === 1'b1) ? reg_289 : ap_const_lv32_0);

assign tmp_9_i_i_fu_599_p2 = tmp_2_i_i_fu_541_p1 << tmp_6_i_i_fu_589_p1;

assign tmp_9_to_int_fu_468_p1 = tmp_9_reg_880;

assign tmp_i_i_i_cast_fu_545_p1 = loc_V_fu_519_p4;

assign x_assign_fu_509_p3 = ((tmp_19_reg_887[0:0] === 1'b1) ? tmp_9_reg_880 : ap_const_lv32_44480000);

assign y_load_1_phi_fu_707_p3 = ((sel_tmp4_fu_662_p2[0:0] === 1'b1) ? x_assign_reg_892 : sel_tmp6_fu_699_p3);

assign y_load_phi_fu_398_p3 = ((sel_tmp2_fu_379_p2[0:0] === 1'b1) ? y_1_load_reg_826 : sel_tmp5_fu_392_p3);


endmodule //Dig_compensator

